/*
 * This Java source file was generated by the Gradle 'init' task.
 *
 * TODO: move some of static functions to other classes
 */
package oop.homework1030;

import java.util.ArrayList;
import java.util.Scanner;

public class App {
  private static InfoPublisher<ArrayList<StudentInfo>> publisher;
  private static ArrayList<StudentInfo> students;

  private static ArrayList<UndergraduateStudent> readUndergraduateStudents() {
    // TODO
    return new ArrayList<UndergraduateStudent>();
  }

  private static ArrayList<GraduateStudent> readGraduateStudents() {
    // TODO
    return new ArrayList<GraduateStudent>();
  }

  private static ArrayList<DoctoralStudent> readDoctoralStudents() {
    // TODO
    return new ArrayList<DoctoralStudent>();
  }

  private static void init() {
    students = new ArrayList<StudentInfo>();

    students.addAll(readUndergraduateStudents());
    students.addAll(readGraduateStudents());
    students.addAll(readDoctoralStudents());

    publisher = new InfoPublisher<ArrayList<StudentInfo>>();

    publisher.subscribe("us", (list) -> {
      // TODO: write new list into the file
      System.out.println("新本科生被添加！");
    });

    publisher.subscribe("gs", (list) -> {
      // TODO: write new list into the file
      System.out.println("新研究生被添加！");
    });

    publisher.subscribe("ds", (list) -> {
      // TODO: write new list into the file
      System.out.println("新博士生被添加！");
    });
  }

  private static String greeting =
    "[A] 打印全部学生信息\n" +
    "[B] 新增一个本科生\n" +
    "[C] 新增一个研究生\n" +
    "[D] 新增一个博士生\n" +
    "[E] 按学号查找学生\n" +
    "[F] 按姓名查找学生\n" +
    "[G] 学生排序\n" +
    "[Z] 结束程序\n";

  private static String prompt = ">>> ";

  private static void run() {
    System.out.println(greeting);

    Scanner scan = new Scanner(System.in);

    while (true) {
      System.out.print(prompt);
      System.out.flush();

      String input = scan.nextLine();

      switch (input) {
        case "A": {
          printAllStudents();
          break;
        }
        case "B": {
          addUndergraduateStudent();
          break;
        }
        case "C": {
          addGraduateStudent();
          break;
        }
        case "D": {
          addDoctoralStudent();
          break;
        }
        case "E": {
          findStudentById();
          break;
        }
        case "F": {
          findStudentByName();
          break;
        }
        case "G": {
          sortStudents();
          break;
        }
        case "Z": {
          scan.close();
          return;
        }
        default: {
          System.err.println("[Error] Unknown command!");
        }
      }
    }
  }

  private static void printAllStudents() {
    // TODO
    System.err.println("[TODO]");
  }

  private static void addUndergraduateStudent() {
    // TODO: add one undergraduate student and produce an event
    publisher.publish("us", students);
    System.err.println("[TODO]");
  }

  private static void addGraduateStudent() {
    // TODO: add one graduate student and produce an event
    publisher.publish("gs", students);
    System.err.println("[TODO]");
  }

  private static void addDoctoralStudent() {
    // TODO: add one doctoral student and produce an event
    publisher.publish("ds", students);
    System.err.println("[TODO]");
  }

  private static void findStudentById() {
    // TODO
    System.err.println("[TODO]");
  }

  private static void findStudentByName() {
    // TODO
    System.err.println("[TODO]");
  }

  private static void sortStudents() {
    // TODO
    System.err.println("[TODO]");
  }

  public static void main(String[] args) {
    init();
    run();
  }
}
